# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/vendor/vendor/vendor.cache/wt [current_project]
set_property parent.project_path E:/vendor/vendor/vendor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  E:/vendor/vendor/vendor.srcs/sources_1/new/fsm.v
  E:/vendor/vendor/vendor.srcs/sources_1/new/f_divider.v
  E:/vendor/vendor/vendor.srcs/sources_1/new/display.v
  E:/vendor/vendor/vendor.srcs/sources_1/imports/new/top_module.v
}
read_xdc E:/vendor/vendor/vendor.srcs/constrs_1/new/main.xdc
set_property used_in_implementation false [get_files E:/vendor/vendor/vendor.srcs/constrs_1/new/main.xdc]

synth_design -top top_module -part xc7a100tcsg324-1
write_checkpoint -noxdef top_module.dcp
catch { report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb }
